# File: .readthedocs.yaml

version: 2

# Build the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Explicitly set the version of Python and its requirements
python:
  version: 3.7
  setup_py_install: true
  install:
    - requirements: docs/requirements.txt